### ISSUE TITLE
[iOS] Making Sure that the App Is Properly Signed (MSTG‑CODE‑1)

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mastg#1347]
**Describe the issue**

The test case for "Making Sure that the App Is Properly Signed (MSTG‑CODE‑1)" for iOS is only an overview without much information on what to do with the codesign output. 

It should describe what to look out for in codesign output and how to verify that it wasn't modified. 

**Optional: Testcase or section**
### Making Sure that the App Is Properly Signed (MSTG‑CODE‑1) in 0x06i 
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06i-Testing-Code-Quality-and-Build-Settings.md#making-sure-that-the-app-is-properly-signed

**Comment by cpholguera** [comment]
This was improved some time ago: https://mas.owasp.org/MASTG/tests/ios/MASVS-RESILIENCE/MASTG-TEST-0081/ 

> You have to ensure that the app is [using the latest code signature format ↗](https://developer.apple.com/documentation/xcode/using-the-latest-code-signature-format). You can retrieve the signing certificate information from the application's .app file with [codesign ↗](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html).
