### ISSUE TITLE
Extend user education testcase based on MSTG‑ARCH‑12

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mastg#1491]
MSTG‑ARCH‑12: The app should comply with privacy laws and regulations. 
Furthermore, based on this, the following actions need to be taken:
- [ ] Extend user education section 
- [x] Extend explanation on that this includes not having location data in images and tracking, unless that is consented by the user (https://github.com/OWASP/owasp-masvs/issues/298). Next, make sure we show how to remove exif data.
- [x] Extend explanation on that tracking info should be removed timely as well, this includes location-databases,images with location info, etc. https://github.com/OWASP/owasp-masvs/issues/281

**Comment by cpholguera** [comment]
Related to #1988

**Comment by cpholguera** [comment]
MASVS-ARCH removed for MASVS 2.0

MASVS-STORAGE-5 takes care of this.
