### ISSUE TITLE
QA - Review 1500

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#1519]
Do the second round of QA over: https://github.com/OWASP/owasp-mstg/pull/1500

**Comment by commjoen** [comment]
Let's just put all prs here that need a second round :-) (eg extend the issue as required)

**Comment by sushi2k** [comment]
@cpholguera Was this already done?

**Comment by cpholguera** [comment]
Hi Sven, no, #1500 still needs a second round :)

**Comment by cpholguera** [comment]
@TheDauntless, whenever you have time, could you please give this a look? If you think everything in that PR was right we can close this one.
