### ISSUE TITLE
Captions for pictures

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mastg#1577]
**Describe the issue**

At the moment there are no captions for pictures. There are various ways of doing captions. The following 2 are both violating markdown lint rules:

![image](https://user-images.githubusercontent.com/5951320/68999909-68bca700-0902-11ea-94a4-77f8cae6ec20.png)

To-Do:

- [ ]  Need to discuss what options for captions are available and which one we want to use
- [ ] Apply consistently throughout the MSTG

Ressources:
http://sparkandshine.net/en/insert-images-with-captions-in-markdown/
https://stackoverflow.com/questions/19331362/using-an-image-caption-in-markdown-jekyll

**Comment by cpholguera** [comment]
Captions appear if alt text is included
