### ISSUE TITLE
Add short intro to bytecodeviewer and fix word bytecode

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#1704]
It's just mentioned in 0x08.

- Add short intro to bytecodeviewer.com in 0x05b-Basic-Security_Testing.md. First draft:

> Bytecodeviewer is a free and open source Java decompiler framework running on all Operating Systems. You can use it to decompile Android apps, view APK Resources (via apktool), easily edit APKs (via Smali/Baksmali), open APKs, DEX, Java Class Files and Java Jars, among many other features. One of the main advantages that it provides is the integration with multiple decompilers including DJ-GUI/Core, Procyon, CFR, Fernflower, Krakatau, and JADX-Core. This is very important because some decompiles might fail when decompiling while others might be able to deliver results. With bytecodeviewer you don't need to run all decompilers separately.

- Fix word "byte-code", "byte code", etc. It should be "bytecode" as per Android Docs. Fix also in the style-guide.md

**Comment by su-vikas** [comment]
@cpholguera  this one can be closed.

**Comment by manan1979** [comment]
can i work on this issue? if yes then how can you define first draft in 0x05b.

**Comment by cpholguera** [comment]
Hi @manan1979, this one's already done. We just forgot to close it. But feel free to take another one, thank you!

**Comment by DIEGOHJ566** [comment]
> It's just mentioned in 0x08.
> 
> 
> 
> - Add short intro to bytecodeviewer.com in 0x05b-Basic-Security_Testing.md. First draft:
> 
> 
> 
> > Bytecodeviewer is a free and open source Java decompiler framework running on all Operating Systems. You can use it to decompile Android apps, view APK Resources (via apktool), easily edit APKs (via Smali/Baksmali), open APKs, DEX, Java Class Files and Java Jars, among many other features. One of the main advantages that it provides is the integration with multiple decompilers including DJ-GUI/Core, Procyon, CFR, Fernflower, Krakatau, and JADX-Core. This is very important because some decompiles might fail when decompiling while others might be able to deliver results. With bytecodeviewer you don't need to run all decompilers separately.
> 
> 
> 
> - Fix word "byte-code", "byte code", etc. It should be "bytecode" as per Android Docs. Fix also in the style-guide.md
