### ISSUE TITLE
UnCrackable-Level3.apk  not resolvable using a known solution 

### ISSUE THREAD

**Issue by aoprea1982** [OWASP/owasp-mastg#1795]
**Describe the bug**

UnCrackable-Level3.apk  not resolvable using a known solution 

apk: UnCrackable-Level3.apk [https://github.com/OWASP/owasp-mstg/tree/master/Crackmes/Android/Level_03](url)
Tools: [https://github.com/enovella/androidtrainings/tree/master/owasp-crackmes/level3/hooks](url)
     ```
     run_usb_spawn.py
      hooks.js
    ```

Using the solution from [https://enovella.github.io/android/reverse/2017/05/20/android-owasp-crackmes-level-3.html](url)
and changing  the offset for the native implementation of the functions in libfoo.so to match the current apk. 

hook.js
```
var offset_protect_secret64 = 0x000010e0;
var offset_strncmp_xor64    = 0x00003478;
```

Keep getting the following errors:

``` 
[!] Received: [ptr_strncmp_xor64  @ 0x7adad687ec]
Error: access violation accessing 0x7adad687ec
    at frida/runtime/core.js:387
    at do_native_hooks_libfoo (/script1.js:117)
    at /script1.js:136
[!] Received: [sg.vantagepoint.util.RootDetection.checkRoot1()Z  Root check 1 HIT!  su.exists()]
[!] Received: [sg.vantagepoint.util.RootDetection.checkRoot2()Z  Root check 2 HIT!  test-keys]
[!] Received: [sg.vantagepoint.util.RootDetection.checkRoot3()Z  Root check 3 HIT!  Root packages]
[!] Received: [sg.vantagepoint.util.IntegrityCheck.isDebuggable(Landroid/content/Context;)Z  Debug check HIT! ]
[!] Received: [MainActivity.onStart() HIT!!!]
[!] Received: [pthread_create() overloaded]
[!] Received: [loading real pthread_create()]
[!] Received: [libfoo.so          @ 0x7adad61000]
[!] Received: [ptr_strncmp_xor64  @ 0x7adad687ec]
Error: access violation accessing 0x7adad687ec
    at frida/runtime/core.js:387
    at do_native_hooks_libfoo (/script1.js:117)
    at /script1.js:136
ReferenceError: identifier 'haystack' undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:83853)
    at /script1.js:40
................................
[!] Received: [pthread_create() overloaded]
[!] Received: [loading real pthread_create()]
[!] Received: [libfoo.so          @ 0x7adad61000]
[!] Received: [ptr_strncmp_xor64  @ 0x7adad687ec]
Error: access violation accessing 0x7adad687ec
    at frida/runtime/core.js:387
    at do_native_hooks_libfoo (/script1.js:117)
    at /script1.js:136
[!] Received: [pthread_create() overloaded]
[!] Received: [loading real pthread_create()]
[!] Received: [libfoo.so          @ 0x7adad61000]
[!] Received: [ptr_strncmp_xor64  @ 0x7adad687ec]
Error: access violation accessing 0x7adad687ec
    at frida/runtime/core.js:387
    at do_native_hooks_libfoo (/script1.js:117)
    at /script1.js:136
ReferenceError: identifier 'haystack' undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:83853)
    at /script1.js:40
[!] Received: [pthread_create() overloaded]
[!] Received: [loading real pthread_create()]
[!] Received: [libfoo.so          @ 0x7adad61000]
[!] Received: [ptr_strncmp_xor64  @ 0x7adad687ec]
Error: access violation accessing 0x7adad687ec
    at frida/runtime/core.js:387
    at do_native_hooks_libfoo (/script1.js:117)
    at /script1.js:136
[!] Received: [MainActivity.onStart() HIT!!!]
[!] Received: [pthread_create() overloaded]
[!] Received: [loading real pthread_create()]
[!] Received: [libfoo.so          @ 0x7adad61000]
[!] Received: [ptr_strncmp_xor64  @ 0x7adad687ec]
Error: access violation accessing 0x7adad687ec
    at frida/runtime/core.js:387
    at do_native_hooks_libfoo (/script1.js:117)
    at /script1.js:136
ReferenceError: identifier 'haystack' undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:83853)
    at /script1.js:40


```
**crackme or other challenge**
UnCrackable-Level3.apk [https://github.com/OWASP/owasp-mstg/tree/master/Crackmes/Android/Level_03](url)

**To Reproduce**

1. Use the scripts from [https://github.com/enovella/androidtrainings/tree/master/owasp-crackmes/level3/hooks](url)
      run_usb_spawn.py
      hooks.js

2. Change the offset of the native functions  in libfoo.so to match the current apk. 

hook.js
```
var offset_protect_secret64 = 0x000010e0;
var offset_strncmp_xor64    = 0x00003478;
```

3.  Run the following command and see the errors

```
python run_usb_spawn.py owasp.mstg.uncrackable3
```

**Expected behavior**
The native hooking should work and obtain the secret as in [https://enovella.github.io/android/reverse/2017/05/20/android-owasp-crackmes-level-3.html](url)

**Additional context**
fridaVersion: 12.11.4
testingDevices: Nexus5X Android 7.1.1; Genymotion Android 9.0 

Played with some offset values but still getting the errors.

Thank you!

**Comment by sushi2k** [comment]
You could try an older Frida version, just to check that it's not something that has changed in Frida. So give it a try with a frida version that was available when this solution was published.

**Comment by sahildhar** [comment]
Hi @aoprea1982 , the solution won't work anymore as the code for the app has probably changed during compilation. For example: as per the assembly of libfoo.so there is no such function like "strncmp_xor64" which takes two arguments. Now we have only one function with one argument which is the secret value to protect. 

If you carefully read the solution, the offset "offset_protect_secret64" is not even used any where in the script. If you are planning to use frida for the solution, i have written the following script to solve this challenge. The script will print the secret value, that you will need to xor with already known xor key to get the flag.

`function disable_java_checks() {
    var System = Java.use('java.lang.System');
    System.exit.implementation = function (arg) {
        console.log('exit called, original return value: ' + arg.toString());
    }

}

function disable_native_checks() {
    var pthread_create_ptr = new NativePointer(Module.findExportByName("libc.so", "pthread_create"));
    var pthread_create = new NativeFunction(pthread_create_ptr, 'int', ['pointer', 'pointer', 'pointer', 'pointer']);

    Interceptor.replace(pthread_create_ptr, new NativeCallback(function (arg0, arg1, arg2, arg3) {
        var ret = ptr(0);
        if (arg1 == 0x0 && arg3 == 0x0) {
            console.log('[+] Bypassed monitor and anti debug threads');
        } else {
            ret = pthread_create(arg0, arg1, arg2, arg3);
        }

        extract_secret();

    }, "int", ['pointer', 'pointer', 'pointer', 'pointer']));
}

function extract_secret() {
    var libfoo_base = Module.findBaseAddress("libfoo.so");
    var secret_func = new NativePointer(libfoo_base.add(0x10e0))

    console.log("{+} libfoo base is at " + libfoo_base.toString());
    Interceptor.attach(secret_func, {
        onEnter: function (args) {
            console.log("secret value variable is at " + args[0].toString());
            this.arg0 = args[0]
        },
        onLeave: function (retval) {
            console.log(this.arg0);
            console.log(
                hexdump(ptr(this.arg0), { offset: 0, length: 24, header: false, ansi: true })
            );
        }
    });
}


Java.perform(function () {
    const System = Java.use("java.lang.System");
    const Runtime = Java.use("java.lang.Runtime");
    const VMStack = Java.use("dalvik.system.VMStack");

    System.loadLibrary.implementation = function (lib) {
        try {
            if (lib == "foo") {

                console.log("libfoo is loaded");
                disable_native_checks();
                disable_java_checks();
            }

            var loaded = Runtime.getRuntime().loadLibrary0(VMStack.getCallingClassLoader(), lib);
            return loaded;
        } catch (ex) {
            console.log("[!] loadLibrary exception: " + ex);
        }
    };

});`

**Comment by cpholguera** [comment]
Thanks for the great answer @sahildhar!
