### ISSUE TITLE
Update to Yaml

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mastg#1872]
**Describe the issue**
Add additional meta-data to our existing markdown description.

Mixture of Yaml and Markdown:
https://raw.githubusercontent.com/OWASP/owasp-mstg/master/.github/ISSUE_TEMPLATE/bug-report---error-in-app.md 

Can still be read in Python @TheDauntless what was the library?

Front Matter https://jekyllrb.com/docs/front-matter/

Pro

- [ ] Can we collect keywords that could be used for a regex for tools?
- [ ] Easier creation of reference list (end of the chapter) with Yaml?

Con

- [ ] Would Gitbook still work?

Would such a feature make sense?

```
---
linka = nviso.be
---

I work at [linka] xxx
```

**Comment by cpholguera** [comment]
We're already doing this as part of the MASTG refactoring.
