### ISSUE TITLE
[Technique] Taint Analysis

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#1942]
Include Taint Analysis in our techniques.

https://www.usenix.org/system/files/sec20-elsabagh.pdf

### GDA?

GDA supports Static Taint Analysis:
https://github.com/charles2gan/GDA-android-reversing-Tool/wiki/GDA-Static-Taint-Analysis

Among many other features, it has this Frida support:
https://github.com/charles2gan/GDA-android-reversing-Tool/wiki/GDA-support-for-the-frida

### Other tools
Do we have other tools already doing this? e.g. RMS. What about FlowDroid?

**Comment by su-vikas** [comment]
Taking this one up.

**Comment by su-vikas** [comment]
@cpholguera Shall I put this in Binary analysis section, after symbolic execution? https://github.com/OWASP/owasp-mastg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#binary-analysis

**Comment by cpholguera** [comment]
Hi Vikas, it'd be great if you could already draft the content. We're currently refactoring the MASTG chapters to a new format so for now, you can put it there on your branch but we'll ask you to pull from master and move your content before merging. Is that ok for you?

**Comment by su-vikas** [comment]
Got it. I will keep the content on my branch for now.

**Comment by su-vikas** [comment]
@cpholguera  I have created a PR so that you know the content is ready. I can update it as per your above comment.

**Comment by cpholguera** [comment]
Thanks a lot @su-vikas!
