### ISSUE TITLE
Decrypting Realm Databases

### ISSUE THREAD

**Issue by R3zk0n** [OWASP/owasp-mastg#1951]
**Proposal to add to a section**
Adding to section [0x06-d - Realm Databases](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06d-Testing-Data-Storage.md#realm-databases)

### Decrypting Realm Databases
However Realm Databases have a notable issue when using the encrypted method, The encryption key is also the decryption key. If a user is able to obtain the key that is used to encryption they are able to decrypt the database and view the contents contained in it. This is trivial to do with a simple Frida script for both iOS & Android.

Resources for Android: [Enter The Realm](https://x64.sh/mobile/security/2020/12/21/Enter-The-Realm/)

**Comment by cpholguera** [comment]
Hi @R3zk0n, thanks a lot for your suggestion, could you please open a PR with that?

> ⭐ Tip: for a one line edit you can do it directly in GitHub by going to the file and clicking on "Edit file".
>
> Alternatively you can [navigate to the file and press "."](https://twitter.com/github/status/1425505817827151872?t=IKc3a2GzeF3f9W1RLbzKoA&s=19), you'll be presented with an online vscode where you can do and commit your changes and even open a PR from there.
