### ISSUE TITLE
Add Tech Writing Training to style guide

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2007]
Our style guide: https://github.com/OWASP/owasp-mastg/blob/master/docs/contributing/5_Style_Guide.md

Add these trainings as an [mkdocs admonition of type "tip"](https://squidfunk.github.io/mkdocs-material/reference/admonitions/):

```
We recommend you to take these free Google courses when writing or reviewing content for the MAS project:

- [Technical Writing One](https://developers.google.com/tech-writing/one)
- [Technical Writing Two](https://developers.google.com/tech-writing/two)
```

**Comment by Amod02-prog** [comment]
Hi , I would like to work on this issue . Do you want to add Tech Writing Training as  a separate heading.

**Comment by cpholguera** [comment]
Hi @Amod02-prog, I've updated the description, I hope that helps. No need for a separate header you can put this right before "## 1. How to Write Content". Thank you!
