### ISSUE TITLE
[Tool] Add jadx to Frida Integration

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2070]
https://twitter.com/leonjza/status/1495445380292558857?t=o7MgyV0wjMTQe2CLPrie4w&s=19

**Comment by fujiokayu** [comment]
@cpholguera

Thank you for sharing good feature.
This is just a little help for mobile security testing.

From the context menu(right-click menu) of a function that decompiled with jadx-gui, we can generate skeleton code for Frida scripts.
Here is an example with UnCrackable-Level1.

![image](https://user-images.githubusercontent.com/17287988/185618641-dce7992f-8794-4bbe-9412-9de1e76f203f.png)

How about adding a sentence to [Frida CLI and the Java API](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x08a-Testing-Tools.md#frida-cli-and-the-java-api) or / and [jadx](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x08a-Testing-Tools.md#jadx) section?

**Comment by cpholguera** [comment]
That sounds great @fujiokayu, thanks for the suggestion!

**Comment by cgarst** [comment]
I can take this one

**Comment by cpholguera** [comment]
It's yours @cgarst, thanks!
