### ISSUE TITLE
Add tcpdump to 0x06b

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2105]
Add tcpdump (after testing against the latest iOS) and check if there's anything else worth adding from the refs below (sslsplit?).

Refs:
- https://blog.jjhayes.net/wp/2019/02/28/capture-iphone-network-traffic-with-tcpdump-and-wireshark/
- https://iphelix.medium.com/ios-data-interception-b3a393e80c82 (2013, verify that it still works)
- https://www.mustafadur.com/blog/intercepting-ssl-and-https/ (incl. SSLSPLIT)

**Comment by cgarst** [comment]
I can take this one. My thought is to document how tcpdump can be used to capture on the device and stream it via SSH into a PCAP file on the workstation. This is effectively an alternative to the RVI mechanism which doesn't require a USB cable. I can also include instructions for importing the HTTP proxy's private key into Wireshark to decrypt some of the resultant PCAP.

**Comment by cpholguera** [comment]
Sounds great @cgarst, I've assigned it to you. Thank you!
