### ISSUE TITLE
[Bug] Resolve broken link to OWASP MASTG printed version

### ISSUE THREAD

**Issue by chantzlarge** [OWASP/owasp-mastg#2201]
## Description

Discovered broken reference to the OWASP MASTG printed version in [How Can You Contribute?](https://github.com/OWASP/owasp-mastg/blob/master/docs/contributing/1_How_Can_You_Contribute.md) document.

https://github.com/OWASP/owasp-mastg/blob/59ead4803548c5cbd19e2f06b53c1f4f2860f47a/docs/contributing/1_How_Can_You_Contribute.md?plain=1#L81

## Expected Behavior

Link resolves to the OWASP MASTG printed version

## Actual Behavior

Link resolves to "Page Not Found" 

<img width="1728" alt="Screen Shot 2022-09-02 at 10 49 53 AM" src="https://user-images.githubusercontent.com/4284843/188175667-b2090659-e704-4ffd-a1cf-b38a8ac11880.png">

**Comment by cpholguera** [comment]
Thank you @chantzlarge! Now it's fixed ;)
