### ISSUE TITLE
[Bug] Broken links in MASTG Webpage

### ISSUE THREAD

**Issue by AndreMCCarvalho** [OWASP/owasp-mastg#2252]
### MASTG Chapter

0x04g-Testing-Cryptography.md

### File Line Number

90

### Context

The links to "Data Storage on Android"  and "Data Storage on iOS" lead to 404

**Comment by cpholguera** [comment]
Hi @AndreMCCarvalho, I assume there will be more similar broken links. We'll fix them as soon as we can. Thank you very much for reporting!

**Comment by cpholguera** [comment]
Hi @AndreMCCarvalho, links should work now as expected. Please let us know if you find any other issues. We really appreciate that, thank you very much!

**Comment by AndreMCCarvalho** [comment]
No problem! I will! Keep up the good work :+1:
