### ISSUE TITLE
[Suggestions] How can you contribute? page

### ISSUE THREAD

**Issue by p2635** [OWASP/owasp-mastg#2258]
Hi all, I'm new here wanting to learn more about Mobile AppSec. I was reading the page and thought I would give my thoughts on how things can be reworded (with suggestions to changing links below).

Happy to put through a newbie PR since I want to find ways to start contributing. But I want to make sure I follow the process listed on your page before I create them.

UPDATE: Sorry I just realized I broke the rule. This should be posted on the Discussions page first, let me know if I should move all this there.

**Comment by p2635** [comment]
Suggestion 2 - change the call to action link to get people to Github register page

Purpose: Lower the 'barrier to get started', get people to register as soon as possible to contribute. Assume people are intelligent enough to google steps to register if they get stuck.

Original sentence:
> A direct contribution to the MASVS or the MASTG can be done in many different ways. First of all Create a GitHub account (a free one is enough) by following [these steps](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account).

Suggested (I also simplified the sentences):
> You can contribute to the MASVS or MASTG in many different ways! First, go ahead and create a GitHub account for free on the [Github homepage](https://github.com/).

**Comment by p2635** [comment]
**Various suggestions to reduce verbosity**

💬 Participate in Discussions[¶](https://mas.owasp.org/contributing/1_How_Can_You_Contribute/#participate-in-discussions)

Our GitHub [Discussions](https://docs.github.com/en/discussions) are the first place to go for asking questions, giving us feedback and proposing new ideas. If your proposal qualifies for the MASTG/MASVS we'll convert it into an "Issue" (the discussion might take a while).

Suggested (change the -ing to root verb):

Our GitHub [Discussions](https://github.com/OWASP/owasp-mastg/discussions) are the first place to go to ask questions, give feedback, and propose new ideas. If your proposal qualifies for the MASTG/MASVS we'll convert it into an "Issue" (the discussion might take a while).

**Comment by p2635** [comment]
Original:
You can create [Issues](https://github.com/OWASP/owasp-masvs/issues) first for missing requirements, content or errors so that it can be discussed before creating a PR.

- In order to avoid conflicts that several people are working on the same issue without knowing it, the issue will be assigned to one or more people by the project leaders.
- Explain what you think is missing in the issue, including references (if available) and give a suggestion as to where it could be added.

Suggested:
Before creating a PR, first create an [Issue](https://github.com/OWASP/owasp-masvs/issues) to be discussed for missing requirements, content or errors.

- To avoid multiple people duplicating effort on the same issue, the issue will be assigned to one or more people by the project leaders.
- Explain what you think is missing in the issue, including references (if available) and suggest where it could be added.

Changes:
- Prioritised 'Before creating a PR', because that seems more important in the sentence.
- 'In order to' can just be to 'to'
- 'as to' is filler
- 'give a suggestion' can simply be 'suggest'

**Comment by p2635** [comment]
If my suggestions are generally accepted, I will continue to proofread. But I don't want to spend more effort on it, if this is not what you're looking for.

**Comment by cpholguera** [comment]
Hi Phil, first of all thank you very much for taking the time!

This is exactly what we need so please go ahead and suggest anything you think will help us ease/smooth the project onboarding. I really like how you think about the proper wording, the flow of the text, pages and links, etc.

This way of thinking is key if you'd like to start contributing to the MASTG itself. We would like to simplify the guide as much as we can and will be starting a big refactoring very soon. Please let me know if you'd like to participate and I can give you more details.

Welcome to the OWASP MAS project!

**Comment by PhilAtKC** [comment]
That's cool, yes I'm happy to submit a PR. Send me all the details. To give you context, I'm a software tester but I lack technical skills. I'm interested to walk down the path of appsec to hopefully improve my career prospects.

**Comment by cpholguera** [comment]
Awesome, for now I think this is a good place to start so just keep doing what you were doing and open a PR whenever you're ready. Thanks a lot! 🙌

**Comment by p2635** [comment]
Previously replied using the wrong account, reposting my previous comment: "That's cool, yes I'm happy to submit a PR. Let me know if I should just go ahead and do that or send me all the details. To give you context, I'm a software tester but I lack technical skills. I'm interested to walk down the path of appsec to hopefully improve my career prospects."

**Comment by p2635** [comment]
If I have wording suggestions for other pages or components, should I raise individual PRs for them?

**Comment by p2635** [comment]
For example, I have minor suggestions to the header if we want to simplify.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/4522927/193094574-049c6492-c01c-44e2-a2f1-3cfe2053014e.png">

- 'Contributing' can be 'Contribute'
- 'Donations' can be 'Donate'

**Comment by p2635** [comment]
Feel free to ping me about where you need help most (e.g. the refactor), happy to look into that as well.

**Comment by cpholguera** [comment]
As long as the PRs don't get "very big" it's ok to put several corrections in them. I guess you'll get a feeling about it when you've sent a couple of them. And of course I can help you with that, feel free to ask anytime.

**Comment by p2635** [comment]
Is it safe to delete the fork in my repo now?

**Comment by cpholguera** [comment]
Hi @p2635, you may delete the fork but you will need it all the time to open PRs.

**Comment by p2635** [comment]
Ok never mind then, I won't delete it. I thought I might be able to create branches on this repo directly and get rid of my own fork.

**Comment by cpholguera** [comment]
Both PRs are merged now
