### ISSUE TITLE
Website Headers Should be Improved

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2260]
For example, I have minor suggestions to the header if we want to simplify.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/4522927/193094574-049c6492-c01c-44e2-a2f1-3cfe2053014e.png">

- 'Contributing' can be 'Contribute'
- 'Donations' can be 'Donate'

_Originally posted by @p2635 in https://github.com/OWASP/owasp-mastg/issues/2258#issuecomment-1262563283_

(@cpholguera) I'm opening an extra Issue for this because the change won't be trivial. We have to ensure that all possible references to these headers are corrected as well.

**Comment by p2635** [comment]
You have a point. Sounds like a newbie PR I can work on as well, maybe I can give it a go.

**Comment by cpholguera** [comment]
You're right! I've changed the wording, thank you!

I'm thinking that it might be better to have "Docs" instead of "Contribute" and have "Contribute" inside the "Docs".

We might want to include more things in those "Docs" e.g. "how the project is structured", "how to use the MASVS / how to reference it". Any other ideas?

**Comment by p2635** [comment]
'Docs' is too vague for any visitors on the website. I still prefer to have 'Contribute. If you are thinking of including more things, my suggestion is for you to list them all out here first. Then we can categorise and organise after.

- how the project is structured - sounds like it belongs to 'About' but could also be in Contribute (link to About?)
- how to use the MASVS / how to reference it - sounds like it belongs to the main docs for MASVS

**Comment by cpholguera** [comment]
Fair enough, let's then first see what's everything we need / is missing and then we can discuss about where it belongs 👌

**Comment by p2635** [comment]
I've created a simple change now that's only for the nav bar, I hope that is correct
