### ISSUE TITLE
[Bug] Certain anchor links are not working

### ISSUE THREAD

**Issue by p2635** [OWASP/owasp-mastg#2263]
I noticed some links on https://mas.owasp.org/contributing/, go to a link with emojis in them so the anchor does not work (at least on firefox).
![image](https://user-images.githubusercontent.com/4522927/193316647-3b3c0a4f-2693-4848-bfdc-644cc3718944.png)

The whole site might need reviewing to see what links have emojis in the link.

**Comment by cpholguera** [comment]
Thanks @p2635! It should be fixed now in #2282
