### ISSUE TITLE
💲🎉 New Donation

### ISSUE THREAD

**Issue by esRemy** [OWASP/owasp-mastg#2345]
### 🙂 Your Name

Rémy Balangué

### 🏢 Company Name

eShard

### 📧 E-Mail Address

remy.balangue@eshard.com

### 💵 Donation Amount

500

### 📦 Donation Package

Good Samaritan (USD 500; 1 year;  1 paperback MASTG)

### 📘 MASTG Paperback Copies

🌱 No, please save the money for the project and help the environment and climate.

### 📋 Code of Conduct and Donation Conditions

- [X] I agree to follow this project's Code of Conduct and Donation conditions.

**Comment by cpholguera** [comment]
Thank you very much @esRemy!
