### ISSUE TITLE
💲🎉 New Donation

### ISSUE THREAD

**Issue by rsenet** [OWASP/owasp-mastg#2359]
### 🙂 Your Name

Régis SENET

### 🏢 Company Name

ORHUS

### 📧 E-Mail Address

regis.senet@orhus.fr

### 💵 Donation Amount

500

### 📦 Donation Package

Good Samaritan (USD 500; 1 year;  1 paperback MASTG)

### 📘 MASTG Paperback Copies

🌱 No, please save the money for the project and help the environment and climate.

### 📋 Code of Conduct and Donation Conditions

- [X] I agree to follow this project's Code of Conduct and Donation conditions.

**Comment by cpholguera** [comment]
@rsenet this is awesome, thank you so much! Have you already donated by using the link provided here? https://mas.owasp.org/donate/

**Comment by rsenet** [comment]
Yes, done :)

**Comment by rsenet** [comment]
Indeed, here the new uploaded image :) 
![ORHUS](https://user-images.githubusercontent.com/25456431/215798017-2b629d09-8829-4ad0-98dd-8deaec65d57a.png)

**Comment by cpholguera** [comment]
Awesome, we'll update the Donators page and announce it soon!

**Comment by cpholguera** [comment]
https://twitter.com/OWASP_MAS/status/1620770886050795520?t=cyIW8kDxCFECPhCoqaXvjQ&s=19

**Comment by rsenet** [comment]
Hey @cpholguera 
Could you send me the invoice by mail please?
Trying to contact support@owasp.com but never received any answer
Thanks

**Comment by cpholguera** [comment]
Sure, I haven't access to that but I've sent an internal request for you.

**Comment by rsenet** [comment]
Thanks a lot
