### ISSUE TITLE
Investigate dual-language code boxes

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-mastg#2384]
We should investigate if we can join different code snippets into a single visual element, just like on Android developer documentation:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/1650034/219647549-971f056d-70bf-490e-b619-4a4a27d095f3.png">

We do have to make sure that this is also displayed correctly in the PDF.

**Comment by cpholguera** [comment]
That's already possible thanks to the Snippets plugin and hooks
