### ISSUE TITLE
MAS Checklist

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mastg#2467]
There is a bug in the MAS Checklist, when the dropdown menu is selected the cells above are highlighted with the colour but not the cell where the value was selected. 

![image](https://github.com/OWASP/owasp-mastg/assets/5951320/53edfd4a-273b-404b-acf8-6f9868e15b2c)

**Comment by cpholguera** [comment]
Duplicate of: https://github.com/OWASP/owasp-mastg/issues/2454
