### ISSUE TITLE
[Bug] Incorrectly refers to 'Resource Owner' instead of 'Resource Server'

### ISSUE THREAD

**Issue by rsporsche** [OWASP/owasp-mastg#2510]
### MASTG Chapter

0x04e-Testing-Authentication-and-Session-Management.md

### File Line Number

188

### Context

The document states "Resource Owner and Authorization Server roles". I believe this should be "Resource Server and Authorization Server roles". Note that the digital ocean page linked from this section uses the following text: "resource and authorization server roles"

**Comment by cpholguera** [comment]
Thanks @rsporsche. I think the current text is correct. If you read the RFC it defines those roles. See here:

https://datatracker.ietf.org/doc/html/rfc6749#section-1.1

```
OAuth defines four roles:

   resource owner
      An entity capable of granting access to a protected resource.
      When the resource owner is a person, it is referred to as an
      end-user.

   resource server
      The server hosting the protected resources, capable of accepting
      and responding to protected resource requests using access tokens.

   client
      An application making protected resource requests on behalf of the
      resource owner and with its authorization.  The term "client" does
      not imply any particular implementation characteristics (e.g.,
      whether the application executes on a server, a desktop, or other
      devices).

   authorization server
      The server issuing access tokens to the client after successfully
      authenticating the resource owner and obtaining authorization.
```

**Comment by cpholguera** [comment]
Hi @rsporsche, I've double checked and I think you're right. The API is definitely not the user (resource owner). Would you mind opening a PR to correct that? Thank you very much for reporting it!

**Comment by cpholguera** [comment]
If you find any other bugs, if you could report them using a link that'd be very helpful. Thanks a lot!

Something like 


https://github.com/OWASP/owasp-mastg/blob/0cc62ca7b9e5b7f008bae56bdad9ca23b6f00c6d/Document/0x04e-Testing-Authentication-and-Session-Management.md?plain=1#L188

**Comment by rsporsche** [comment]
> Hi @rsporsche, I've double checked and I think you're right. The API is definitely not the user (resource owner). Would you mind opening a PR to correct that? Thank you very much for reporting it!

Please excuse my ignorance, is a PR a pull request?
