### ISSUE TITLE
Broken Links in MASVS-CODE/MASTG-TEST-0025

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2561]
In https://mas.owasp.org/MASTG/tests/android/MASVS-CODE/MASTG-TEST-0025/
the links at the top are rendered as:

[Testing Deep Links](https://mas.owasp.org/MASTG/tests/android/MASVS-CODE/MASTG-TEST-0025/)
[Testing for Sensitive Functionality Exposure Through IPC](https://mas.owasp.org/MASTG/tests/android/MASVS-CODE/MASTG-TEST-0025/)
[Testing for Overlay Attacks](https://mas.owasp.org/MASTG/tests/android/MASVS-CODE/MASTG-TEST-0025/)

The actual markdown is:

```md
## Overview

To test for [injection flaws](../../../Document/0x04h-Testing-Code-Quality.md#injection-flaws "Injection Flaws") you need to first rely on other tests and check for functionality that might have been exposed:

- ["Testing Deep Links"](../../../tests/android/MASVS-PLATFORM/MASTG-TEST-0028.md)
- ["Testing for Sensitive Functionality Exposure Through IPC"](../../../tests/android/MASVS-PLATFORM/MASTG-TEST-0029.md)
- ["Testing for Overlay Attacks"](../../../tests/android/MASVS-PLATFORM/MASTG-TEST-0035.md)
````

which is correct.

**Comment by sk3l10x1ng** [comment]
> In https://mas.owasp.org/MASTG/tests/android/MASVS-CODE/MASTG-TEST-0025/ the links at the top are rendered as:
> 
> [Testing Deep Links](https://mas.owasp.org/MASTG/tests/android/MASVS-CODE/MASTG-TEST-0025/) [Testing for Sensitive Functionality Exposure Through IPC](https://mas.owasp.org/MASTG/tests/android/MASVS-CODE/MASTG-TEST-0025/) [Testing for Overlay Attacks](https://mas.owasp.org/MASTG/tests/android/MASVS-CODE/MASTG-TEST-0025/)
> 
> The actual markdown is:
> 
> ```
> ## Overview
> 
> To test for [injection flaws](../../../Document/0x04h-Testing-Code-Quality.md#injection-flaws "Injection Flaws") you need to first rely on other tests and check for functionality that might have been exposed:
> 
> - ["Testing Deep Links"](../../../tests/android/MASVS-PLATFORM/MASTG-TEST-0028.md)
> - ["Testing for Sensitive Functionality Exposure Through IPC"](../../../tests/android/MASVS-PLATFORM/MASTG-TEST-0029.md)
> - ["Testing for Overlay Attacks"](../../../tests/android/MASVS-PLATFORM/MASTG-TEST-0035.md)
> ```
> 
> which is correct.

@cpholguera  Try using the path with one directory backward
```
- ["Testing Deep Links"](../MASVS-PLATFORM/MASTG-TEST-0028.md)
- ["Testing for Sensitive Functionality Exposure Through IPC"](../MASVS-PLATFORM/MASTG-TEST-0029.md)
- ["Testing for Overlay Attacks"](../MASVS-PLATFORM/MASTG-TEST-0035.md)
```

**Comment by cpholguera** [comment]
Good point, thanks!
