### ISSUE TITLE
[Bug] Broken link in MASVS-RESILIENCE/MASTG-TEST-0050.md

### ISSUE THREAD

**Issue by chagemann** [OWASP/owasp-mastg#2569]
### MASTG Chapter

MASVS-RESILIENCE/MASTG-TEST-0050

### File Line Number

21

### Context

link to `Tampering and Reverse Engineering on Android` returns `404`

---

The link points to `../../../Document/0x05c-Reverse-Engineering-and-Tampering.md` which was removed in https://github.com/OWASP/owasp-mastg/pull/2439:
> Removed chapters 0x05c and 0x05c (content split into individual techniques for the Techniques section and merged to 0x05b and 0x06b for the PDF)

I also noticed [0x04c-Tampering-and-Reverse-Engineering.md](https://github.com/OWASP/owasp-mastg/blob/master/Document/0x04c-Tampering-and-Reverse-Engineering.md) which seems to be a better fit than [0x05b](https://github.com/OWASP/owasp-mastg/blob/master/Document/0x05b-Android-Security-Testing.md).

A full text search of `0x05c-Reverse-Engineering-and-Tampering.md` reveals 37 matches in 25 files.

Happy to submit a PR if you could give me guidance on the replacement link.

**Comment by cpholguera** [comment]
Hi @chagemann, thanks for reporting this and sorry for the delay in responding. I've investigated the issue further and we have the same situation with the corresponding iOS chapter. 

Thanks for volunteering to fix the problem! To make things easier for you, I've started the fixes [here](https://github.com/OWASP/owasp-mastg/pull/2607). You can continue the work on the `fix-broken-links-to-5c-6c` branch (if you cannot push to that branch, just let me know).


I used vscode to search for all links:

<img width="1069" alt="image" src="https://github.com/OWASP/owasp-mastg/assets/29175115/fba91d9c-89da-4b7e-beba-373fe17f746a">

See this example in the screenshot:

```md
> This repackaging method is enough for most use cases. For more advanced repackaging, refer to
 ["Android Tampering and Reverse Engineering - Patching, Repackaging and Re-Signing"](0x05c-Reverse-Engineering-and-Tampering.md#patching-repackaging-and-re-signing).
```

You can use the title "Patching, Repackaging and Re-Signing" or the anchor "#patching-repackaging-and-re-signing" to search for the right technique in https://mas.owasp.org/MASTG/techniques/

In this case, among the Android techniques you can find: "MASTG-TECH-0039: Repackaging & Re-Signing"

<img width="1555" alt="image" src="https://github.com/OWASP/owasp-mastg/assets/29175115/d37f5367-98e6-484b-8621-6e5a5f97de10">


So the fixed text would be:

```md
> This repackaging method is enough for most use cases. For more advanced repackaging, refer to
 ["Repackaging & Re-Signing"](../../techniques/android/MASTG-TECH-0039.md "Repackaging & Re-Signing")
```

**Comment by cpholguera** [comment]
Hi @chagemann, will you be able to continue the work here: https://github.com/OWASP/owasp-mastg/pull/2607? Should I assign it to you? Thanks!

**Comment by chagemann** [comment]
@cpholguera Yes, please assign it to me.

**Comment by cpholguera** [comment]
@chagemann I've invited you to the project. Once you accept I'll assign it to you. Thanks so much!

**Comment by chagemann** [comment]
@cpholguera Thank you - invite accepted.

**Comment by cpholguera** [comment]
Thanks! It's assigned to you now ✅

**Comment by chagemann** [comment]
@cpholguera Could you please check my permissions:
```
> owasp-mastg git:(fix-broken-links-to-5c-6c) git status
On branch fix-broken-links-to-5c-6c
Your branch is ahead of 'origin/fix-broken-links-to-5c-6c' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
> owasp-mastg git:(fix-broken-links-to-5c-6c) git push
ERROR: Permission to OWASP/owasp-mastg.git denied to chagemann.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by cpholguera** [comment]
@chagemann I'm going to merge this one and you can open another PR for the same ticket and continue the work there. That's gonna be easier. Thanks for letting me know!

**Comment by cpholguera** [comment]
It's merged now. You can work on a branch in your fork and open a PR against our master
