### ISSUE TITLE
[MASWE-0013] Hardcoded Cryptographic Keys in Use

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2577]
## Description

Create a new weakness for "Hardcoded Cryptographic Keys in Use (MASVS-CRYPTO-2)" using the following information:

One thing is to include hardcoded keys in the code, another is to use them.

Update https://github.com/OWASP/owasp-mastg/blob/master/weaknesses/MASVS-CRYPTO/MASWE-0013.md including the following content:

```md

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**. Use other MASWE items in `status: new` for reference. For example: MASWE-0027

Use at least the following references:

- <https://developer.android.com/topic/security/risks/hardcoded-cryptographic-secrets>

When creating the corresponding tests, use the following areas to guide you:

- hardcoded keys used at runtime

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.

- [MASTG-TEST-0062 - Testing Key Management (ios)](https://mas.owasp.org/MASTG/tests/ios/MASVS-CRYPTO/MASTG-TEST-0062/)
- [MASTG-TEST-0013 - Testing Symmetric Cryptography (android)](https://mas.owasp.org/MASTG/tests/android/MASVS-CRYPTO/MASTG-TEST-0013/)

**Comment by ScreaMy7** [comment]
I can work on this. Please assign this to me.

**Comment by ScreaMy7** [comment]
Hi @cpholguera,
Can explain a bit more about test-cases derived from this risk and what the term  "hardcoded keys used at runtime" means here?
We came up with two possible conclusions here, first could be the detection of API tokens and secrets hardcoded in the code and the second conclusion could be the detection of keys of the cryptographic algorithm.
Thanks,

**Comment by cpholguera** [comment]
@ScreaMy7 This comes from the original requirement [MASVS 3.1 (MSTG-CRYPTO-1): "The app does not rely on symmetric cryptography with hardcoded keys as a sole method of encryption."](https://github.com/OWASP/owasp-masvs/blob/v1.5.0/Document/0x08-V3-Cryptography_Verification_Requirements.md)

The fact that "sensitive data is hardcoded in the app package" should be covered by https://github.com/OWASP/owasp-mastg/issues/2543 (which will include crypto keys, API keys and more).

This risk here is about the "use of Cryptographic Keys" specifically.

The tests should be pretty straightforward using as a base the existing MASTG v1 tests linked above. For example, the Android illustrates this case: https://mas.owasp.org/MASTG/tests/android/MASVS-CRYPTO/MASTG-TEST-0013/

So basically the work to be done here is:

- Create a risk (generic about the risk)
- Create a test for Android (mentioning specific [Android crypto APIs](https://mas.owasp.org/MASTG/Android/0x05e-Testing-Cryptography/))
  - Create one example for the static test
  - Create one example for the dynamic test
- Create a test for iOS (mentioning specific [iOS crypto APIs](https://mas.owasp.org/MASTG/iOS/0x06e-Testing-Cryptography/))
  - Create one example for the static test
  - Create one example for the dynamic test
 
Here are 2 existing risks including static and dynamic tests which you can use as a reference:
- Static / semgrep: [risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/](https://github.com/OWASP/owasp-mastg/tree/master/risks/MASVS-CRYPTO/1-strong-crypto/insecure-random)
- Dynamic / frida-trace: [risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs](https://github.com/OWASP/owasp-mastg/tree/master/risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs)

> Guidelines: https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing
