### ISSUE TITLE
[Tool] Add blutter?

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2619]
Evaluate before adding. Can it be listed as an alternative of reflutter? Or is it essentially different?

> B(l)utter: Flutter Mobile Application Reverse Engineering Tool by Compiling Dart AOT Runtime. Currently the application supports only Android libapp.so (arm64 only). Also the application is currently work only against recent Dart versions.

https://github.com/worawit/blutter

[hitbsecconf2023 slides](https://conference.hitb.org/hitbsecconf2023hkt/materials/D2%2520COMMSEC%2520-%2520B(l)utter%2520%25E2%2580%2593%2520Reversing%2520Flutter%2520Applications%2520by%2520using%2520Dart%2520Runtime%2520-%2520Worawit%2520Wangwarunyoo.pdf)

https://youtu.be/RtKOe8HQy8Q?si=B59P5hQXVrk5J7Sw

**Comment by artembark** [comment]
I think this video is also useful in addition to slides: [B(l)utter – Reversing Flutter Applications](https://www.youtube.com/watch?v=EU3KOzNkCdI)

**Comment by ScreaMy7** [comment]
I used this blutter tool and reflutter on a dummy app to check their differences. These are things which I noticed:

- reflutter does a dynamic runtime analysis by modifying the apk whereas Blutter directly analyzes the libapp.so to extract Dart objects directly from binary and generates frida scripts to dump data in a running Flutter application
- Blutter also produces all symbols name in dart snapshot, offsets etc.
- As just for reversing engineering of the flutter apps I feel Blutter does a much better job.

This may not be the complete list, but these are major advantages blutter has over reflutter. 
@cpholguera  If we add this tool you can assign it to me, as I already have this tool set.

**Comment by cpholguera** [comment]
@ScreaMy7 it's yours, thank you so much!
