### ISSUE TITLE
[Bug] Broken Link to APKiD

### ISSUE THREAD

**Issue by njmulsqb** [OWASP/owasp-mastg#2647]
### MASTG Chapter

Breadcrumbs      owasp-mastg/tests/android/MASVS-RESILIENCE  /MASTG-TEST-0051.md

### File Line Number

63

### Context

When I open the link to APKiD from https://mas.owasp.org/MASTG/tests/android/MASVS-RESILIENCE/MASTG-TEST-0051/#static-analysis the link return 404 not found

**Comment by cpholguera** [comment]
Thank you @njmulsqb, could you please open a PR to fix the issue?

The right link should be: 

/MASTG/tools/android/MASTG-TOOL-0009/

**Comment by cpholguera** [comment]
Fixed in #2848
