### ISSUE TITLE
How to mapping OWASP Mobile Top 10 to CWE

### ISSUE THREAD

**Issue by bernie6401** [OWASP/owasp-mastg#2648]
Dear Crew Staff
I'm a researcher of mobile secuity. OWASP Mobile top 10 is the critical issue to solve and discuss so according to my research, I wonder if there is a mapping table that can help me to map owasp mobile top 10 and CWE or owasp top 10. I survey lots of document and nothing can solve my problem. Could anyone help me if the mapping table exist? Or the inner document can release privately. Thanks a lot.

**Comment by cpholguera** [comment]
Hi @bernie6401 the OWASP Mobile Top 10 is a separate project and not part of the OWASP MAS project.

This is the repo you're looking for, please post your question there so the mobile top 10 team can answer: https://github.com/OWASP/www-project-mobile-top-10

You can find more info and contacts in their project page here: https://owasp.org/www-project-mobile-top-10/
