### ISSUE TITLE
[Tool] Add HTTP Toolkit to Network Tools

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mastg#2793]
Evaluate and potentially incorporate HTTP Toolkit

https://github.com/httptoolkit

### Discussed in https://github.com/OWASP/owasp-mastg/discussions/2665

<div type='discussions-op-text'>

<sup>Originally posted by **saulpanders** July  9, 2024</sup>
[HTTP Toolkit](https://httptoolkit.com/android/)

Its another alternative to Burp proxy, it can intercept HTTP traffic for android devices. It also has some automated abilities to get around certain certificate pinning issues by automatically injecting a system CA on install.

I dont have any affiliation with the tool, but used it recently and found it interesting</div>

**Comment by ScreaMy7** [comment]
@cpholguera Please assign this to me.

**Comment by cpholguera** [comment]
Done, thank you!

**Comment by cpholguera** [comment]
Any news about this @ScreaMy7?

Could you please update the reference here in the technique using the `@MASTG-TOOL-xxxx` notation once it's merged?

https://github.com/OWASP/owasp-mastg/pull/2897
