### ISSUE TITLE
[TOOL] reFlutter

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-mastg#2823]
https://github.com/Impact-I/reFlutter

Should have its own tools page

**Comment by ScreaMy7** [comment]
reFlutter is already added  to tools page here https://github.com/OWASP/owasp-mastg/pull/2600/files#diff-8a2ef0a224b0fe9ee538bc7283df63a5f970cf07dc73c922082a10bd665769bd

**Comment by cpholguera** [comment]
That's right 

https://mas.owasp.org/MASTG/tools/generic/MASTG-TOOL-0100/
