### ISSUE TITLE
Unable to sign android app with all v1, v2, v3 & v4 signing schemes at once.

### ISSUE THREAD

**Issue by vballem** [OWASP/owasp-mastg#2908]
Hi,

I got a bug based on below URL reference from OWASAP that the apk must sign with all versions of signing schemes.

[https://mas.owasp.org/MASTG/tests/android/MASVS-RESILIENCE/MASTG-TEST-0038/](https://mas.owasp.org/MASTG/tests/android/MASVS-RESILIENCE/MASTG-TEST-0038/)

However, I can't be to generate one. I tried with both Android Studio and CLI approaches. 

I am unable to generate signed APK with all versions and also, I nowhere find from android documentation this is possible.

**_Also, how relevant was the suggestions from above [URL](https://mas.owasp.org/MASTG/tests/android/MASVS-RESILIENCE/MASTG-TEST-0038) w.r.t AAB format as google mandates now uploading app-bundles(.aab) which does not support these versions as its totally completely different approach._**

Here is what I have followed to try to sign with all versions of signing-schema 

1. I tried below approaches with a very basic "hello world" sample project directly from Android studio template without no extra coded added.
2. I have created a sample **". keystore"** to sign the release build type variant app. even I tried with debug as well as this is to test.
3. I tried signing with
      4. Android Studio like below

```
defaultConfig {
        minSdk = 29
        targetSdk = 34
    }

 signingConfigs {
            create("mykey") {
                  keyAlias = "my-key-alias"
                  keyPassword = "something"
                   storeFile = file("$projectDir/my-release-key.keystore")
                   storePassword = "something"
                  enableV1Signing = true
                  enableV2Signing = true
                  enableV3Signing = true
                  enableV4Signing = true
           }
     }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("mykey")
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
```

6.  CLI:
```
apksigner sign --ks my-release-key.keystore \
 --ks-key-alias my-key-alias \
 --out app-signed.apk \
 --v1-signing-enabled true \
 --v2-signing-enabled true  \
app-debug-unsigned.apk
```

7. it generated, app-signed.pak
8. verify the signature:
```
 apksigner verify --verbose app-signed.apk 
Verifies
Verified using v1 scheme (JAR signing): false
Verified using v2 scheme (APK Signature Scheme v2): false
Verified using v3 scheme (APK Signature Scheme v3): true
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
```
      
          

I am willing to know based on which which sdk/version the suggestions are given for [MASTG-TEST-0038](https://mas.owasp.org/MASTG/tests/android/MASVS-RESILIENCE/MASTG-TEST-0038/)

and how about with AAB case?.

Appreciate your help

**Comment by vballem** [comment]
@cpholguera thanks for getting back. OK, thanks clarification that the Documation has to be updated.
As i said above, i just took took the new app from wizard and modified the just gradle part.


yes, I am using below config which the latest. 

**1. Android Studio Ladybug | 2024.2.1
2. Android Gradle plugin:  8.7.0
3. Gradle version: 8.9
4. Kotlin version: 2.0.20**

Build Tools tried: 34.0.0, 33.0.0, 35.0.0

even with these, I cant able to sign with just v3 and V4 together.


Also, I would like to know what,s your recommendation for App bundle signing where we dont sign like how we do for APK's.

**Comment by cpholguera** [comment]
V4 does indeed require V3 and V2 to be present. It's stated here:

https://source.android.com/docs/security/features/apksigning/v4

They also indicate that the latest version does this specifically unless you disable V4.

**Comment by vballem** [comment]
@cpholguera what about app bundle signing guidelines from OWASP.  almost every app that uploads to playstore is a .aab now. now one is using APK

do you have any guidelines for app bundle signing.

**Comment by cpholguera** [comment]
The Android docs cover that topic here: https://developer.android.com/studio/publish/app-signing

> When releasing using [Android App Bundles](https://developer.android.com/guide/app-bundle), you need to sign your app bundle with an upload key before uploading it to the Play Console, and Play App Signing takes care of the rest.

Here's how to sign with your upload key: https://developer.android.com/studio/publish/app-signing#sign_release

The recommendation does not change, use the latest available schemes and avoid v1 as much as possible.

**Comment by vballem** [comment]
Yes, I am aware of the Android guidelines.

Thank you so much @cpholguera for your prompt responses.
