### ISSUE TITLE
[Bug] Links about Android App Links Verification not working

### ISSUE THREAD

**Issue by kmaschke85** [OWASP/owasp-mastg#2915]
### MASTG Chapter

https://github.com/OWASP/owasp-mastg/edit/master/tests/android/MASVS-PLATFORM/MASTG-TEST-0028.md

### File Line Number

120-124

### Context

Tried to verify app links in my app, but the links for how to use ADB are not working.

**Comment by cpholguera** [comment]
Thanks for reporting this, @kmaschke85. The links should be working now.
